### ISSUE TITLE
Localization bug?: at Japanese mode, ">>" and "<<"is thin.

### ISSUE THREAD

**Issue by sujiniku** [flareteam/flare-engine#1536]
![screenshot from 2017-12-10 13-44-33](https://user-images.githubusercontent.com/26195610/33802015-9c2eac02-ddb0-11e7-98c1-35999eb1c252.png)
At Japanese mode, ">>" and "<<" in the center of the screen are thin like images. I think that, 16pt fonts may not be applied to this character.

**Comment by dorkster** [comment]
Your screenshot is showing 14pt font size. Here is what 16pt looks like:

![screenshot_2017-12-10_11-09-36](https://user-images.githubusercontent.com/913982/33806754-b6a9fbf6-dd9a-11e7-8854-a4a5abe5a63f.png)

Unfortunately, using 16pt isn't much of an option since it's too big for most of our assets. For example, look at this screenshot:

![screenshot_2017-12-10_11-11-10](https://user-images.githubusercontent.com/913982/33806768-ef015940-dd9a-11e7-93ab-a89577dbb47f.png)

I personally don't think having ">>" and "<<" look thin is too big of a problem. The Mods screen is the only place these characters appear, so it's not essential to gameplay.
