### ISSUE TITLE
Auto-increase resolution?

### ISSUE THREAD

**Issue by vgaming** [flareteam/flare-engine#1591]
The default flare mod, "empyrean campaign", has a default resolution of 640*480.
That's very few to what most monitors provide nowadays.

Question is -- can we do something about that?

For example, we could show all images zoomed 1-to-1, with a much increased visible game area. Like if you increase values written in `fantasycore/engine/resolutions.txt`. If you think further about it, it may be complicated though. Like, suppose you have a 4k monitor with a high pixel density. If you use 1-to-1 image scaling in terms of pixels, the sizes of all images in millimeters will be very small. At the same time, up-scaling a 640x480 image seems a bit insane too. Maybe we should have a "zoom" preference in settings?

I imagine the following "zoom" options might be desired for people:

* scale to fit monitor (default)
* 1x pixel zoom
* 2x pixel zoom
* 3x pixel zoom
* ? auto, to choose pixel zoom automatically based on pixels-per-millimeter data of the monitor ? (this will be hard to implement, so better avoid it for now?)

P.S. Note that pixel zoom may also be easier for eyes. Personally, my eyes get tired of up-scaled images much faster than even smaller 1x images (dunno why, but that's a fact).

Thoughts?

**Comment by dorkster** [comment]
The `virtual_heights` property in resolutions.txt determines what resolution we render at before scaling it to the window size. This allows game designers to restrict the maximum visible play area, regardless of the user's resolution. During the 0.19 days, people using high resolution screens were able to see the entire map, and suffered a performance drop from having to render everything.

Fantasycore assets support 480p and 600p, so if your window is 800x600, pixels will be 1:1. However, I think our policy for when we scale is wrong. We currently do this based on window size:

- window < 480p: render at 480p and scale down
- window >= 480p and window < 600p: **render at 480p and scale up until 600p**
- window >= 600p: render at 600p and scale up until infinity

The problem is the middle step. I think what we should be doing is rendering at the window size's resolution until we're outside the bounds of the virtual heights. 600p allows for the maximum viewing area, so any window size between it and 480p should essentially just be cropping.

Because we try to render at the largest possible resolution, we are always "zoomed out". So any potential options would be to zoom *in*.

I think it is worth looking into adjusting the effective virtual height based on the users screen DPI. My phone has a 5 inch screen and a resolution greater than 600p. So its DPI is MUCH higher than my desktop monitor. It may be worth letting game developers define a `virtual_dpi` as a target we can scale by. We can obtain the monitor's DPI via SDL with [SDL_GetDisplayDPI](https://wiki.libsdl.org/SDL_GetDisplayDPI?highlight=%28%5CbCategoryVideo%5Cb%29%7C%28CategoryEnum%29%7C%28CategoryStruct%29).

**Comment by vgaming** [comment]
@dorkster indeed the window lags on some of the terrain/environment if I increase resolution to 1080p on my notebook. Have to think about it more (currently tired and night time).

**Comment by dorkster** [comment]
You may want to try changing the `renderer` setting in your Flare config.txt file to `sdl_hardware`. On my machine, this performs much better at high resolutions. In reality, this renderer should be made the default.

**Comment by vgaming** [comment]
> You may want to try changing ... to sdl_hardware
indeed that fixed the problem! No more lags even on snowy terrain (this one was a bit laggy before).

**Comment by vgaming** [comment]
@dorkster Thanks for cleaning the issues!
