### ISSUE TITLE
To restore companion's HP with potion and heal magic.

### ISSUE THREAD

**Issue by sujiniku** [flareteam/flare-engine#1593]
At some mod, the hero can summon a companion.
However, it seems that companion's HP restoring method is only by time spending.
I think that it is good to be able to restore companion's HP by items and magic.
Because ordinary player would wants to heal companion if their companion are hurt.

With the ordinary turn-based RPG, the feature that can heal a friend is standard feature.
Perhaps, if this companion recovery feature is available, it may be useful for those who intend to make a turn-based RPG in Flare in the future.

However I have not idea yet how to select a companion to heal.
I think that imitate the method of attack is good. I think that it is good to select a group to heal by the same method as selecting an attacking opponent.

About the case of the potion healing, I think that the mechanism that the hero goes to near comapanion and the hero can heal by pushing the hot key, is natural.

I think that it will not be in time for flare 1.0, but it should add this feature after 1.0.

**Comment by dorkster** [comment]
There's nothing technical preventing us from healing party members. This is how the Minotaur Necromancer heals its skeleton minions.

In the Empyrean campaign, there is one creature that can be summoned via scroll, a level-scaled zombie. As a companion it is quite powerful, so it is intentional that it can not be healed. It is meant to be temporary assistance as opposed to a companion you keep with you the entire game.
