### ISSUE TITLE
Buttons in NPC dialog are not always working

### ISSUE THREAD

**Issue by igorko** [flareteam/flare-engine#1680]
E.g in Udana NPC dialog

**Comment by igorko** [comment]
I cannot reproduce it also now. I will let you know when find reproduce.

**Comment by igorko** [comment]
Happened again. All "buttons" correctly react on hovering (change colors). But some of them do not react on click. It does not depend if it's trade or dialog button. Also after scrolling sometimes it is fixed but not for all items (try Florin when there is a lot of items in the list). Maybe it is because click coordinates and hovering are calculated in different way? And click coordinates incorrectly... By the way: way have you changed "tooltip" dialog that was present in initial implementation to "scrollbox" dialog. Is it because large amount of elements will not fit into the screen?

**Comment by dorkster** [comment]
Interesting. As far as I can tell, there should be no difference between hover and click detection in regards to the mouse position. So something else is likely causing this...

As for "why" these changes were made to the dialog system, there are a couple of reasons:

- Like you said, we're not restricted by screen size for the number of elements that can be listed.
- MenuNPCActions (the old topic chooser) couldn't be displayed while MenuTalker (the main dialog window) was open. This meant we couldn't have context for the presented topics. A simple example would be an NPC asking the player a question with multiple answers. I could have tried getting MenuNPCActions and MenuTalker to have simultaneous visibility, but I think that would have been awkward from a UI perspective.
- It's simpler from a code structure standpoint. Instead of having two menus passing their state between each other, it's all in MenuTalker now. And while not the best metric for "good code", it is ultimately less lines of code.

**Comment by dorkster** [comment]
I think I was able to reproduce this. Or, at least the end result is as you described:

1. Interact with an NPC by using the "ACCEPT" key (space/return by default)
2. Keep the key pressed
3. Try to interact with dialog options. They are highlighted when hovered, but clicks do nothing.

I could see this happening with quick inputs.

**Comment by dorkster** [comment]
I've addressed the Accept key/mouse click conflict in this commit: https://github.com/flareteam/flare-engine/commit/ab2554533cf8a8c34db4ec6693f0054e6be5c6cf

@igorko Do you think this issue can be closed now?

**Comment by igorko** [comment]
I had this issue with mouse only and wasn't using keyboard. I will retest it once again.

**Comment by FeXoR-o-Illuria** [comment]
Might I humbly suggest (though this may not be the proper place) that, if there is only one topic to choose, enter it right away (so e.g. a pure merchant doesn't require 2 clicks to trade with).
There might be edge cases where the player doesn't want to e.g. get a quest but just check if there are quests available from an NPC (in other mods) but there's always the option to add a default "greeting" that would prevent this from happening (so the mod would still have control about if a quest is given right away or can be inspected first).

**Comment by dorkster** [comment]
@FeXoR-o-Illuria Actually, the behavior you described is what happens for non-Trade topics. I've added [a patch](https://github.com/flareteam/flare-engine/commit/1e1461206c79480451a0940a201322b361330f77) that handles pure merchants like they were in v1.08. The only difference now is that it only opens the trade window on the initial interaction. So if the player is talking to the NPC and all the dialog gets finished, they will still be shown the topic selection menu with "Trade" as the option. This lets the player leave without opening the trade windows. If they interact with the same NPC after leaving, it will jump right into the trade window as that counts as a fresh interaction.

**Comment by igorko** [comment]
Closing as I was unable to reproduce it anymore.
