### ISSUE TITLE
Inconsistent behavior of the left mouse button in mouse move mode

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [flareteam/flare-engine#1682]
With "Use mouse to move hero" enabled pressing the left mouse button on free space (not occupied by an enemy) will result in using the assigned skill rather than moving when shortly before a skill was activated (likely while in animation).

To reproduce:
Assign one skill to the left mouse button and another to the right one.
In town (no enemies) right click (right mouse button skill is activated) and directly hold the left mouse button: The character will use the left mouse button skill while he should move (cursor not above enemy).

EDIT:
(This even happens when no skill is assigned to the left mouse button leading in the character just staring at the cursor. However, this is not the only case I'd like to see this fixed but the above mentioned one. This also seams happen in "hit recovery" animation making it impossible to flee)

May be related to #1681  which also seems to input causing different actions depending on the character's animation state.

**Comment by dorkster** [comment]
I believe I made a mistake here. The original behavior was intentional because accidentally moving the mouse off of an enemy would make the player start running when they want to be attacking. Granted, this can be mitigated by holding Shift, but it was still requested at one point. My patch nullified the original behavior, but I don't want to revert it. I think the appropriate solution would be to add a small time buffer in between when the *might* want to start moving after attacking and when they actually *do* start moving.

**Comment by FeXoR-o-Illuria** [comment]
What I would like to see would be something like:
- Left mouse button pressed with cursor above the enemy and held: Move into range, if in range attack towards the enemy (all independent of the cursor position), if enemy dies, stop.
Similar: Left mouse button pressed with cursor above non-hostile interactable (chest, door, NPC, item) and held: Move into range, use (speak to, open, take, etc.), if done, stop.
- Left mouse button pressed with cursor above ground and held: Run towards the cursor position independent of the cursor being above anything that can be interacted with. In this state the Shift key can be used to attack in the direction of the cursor and, if released, resume running.


So if you "target" something it's basically "do what I want" dependent on target (which ofc. would fail quite often without e.g. using pathfinding but I think the player will figure out he has to use manual control to reach a sufficient position). If nothing is "targeted" you enter a mode the cursor position is what you run towards/aim at - and where Shift has that important roll of toggling between running and attacking..

I'll test 1.08.20. see if anything comes to mind.

(In Diablo II with a melee-attack on the right mouse button made you chase the cursor until an enemy is in range - then switch to attack the enemy with the lowest ID in range and after everything in range is dead continue running. I loved that but it's not the first thing I'd implement - but for melee fighters Flare in it's current state is a pain.)

**Comment by dorkster** [comment]
Let's consider the various states of the left mouse button (MAIN1):

|MAIN1 state|Empty ground|Object/NPC/etc|Melee attack on enemy|Ranged attack on enemy
|-----|-----|-----|-----|-----|
|**Not held/new press**|Move in cursor direction.|If in range, do interaction. Else move in cursor direction.|If in range, attack enemy. Else move in cursor direction.|Begin attacking.
|**Held**|Move in cursor direction.|Move in cursor direction.|If in range, attack enemy. Else move in cursor direction.|Move in cursor direction.
|**Not held/new press + holding Shift**|Begin attacking.|Do interaction.|Begin attacking.|Begin attacking.
|**Held + holding Shift**|Begin attacking.|Do interaction. *Bug: NPCs appear to not activate in this condition.*|Begin attacking.|Begin attacking.

There's a few here I want to address:

- **Held + Object**: This is intentional to prevent the player from accidentally triggering events while dragging around.
- **(Not) Held + Ranged attack**: These should probably behave like melee attacks, but the engine doesn't currently calculate the effective range for ranged attacks. Calculating these distances should be feasible given a Power's lifetime and speed.
- **Held + Shift + Object**: We definitely want to make this more consistent. So either fix NPC interaction or make Shift always begin attacking regardless of if MAIN1 is held.

Aside from the last two bullet points, I'm fairly happy with the current behavior.

**Comment by FeXoR-o-Illuria** [comment]
I played around a bit trying to get the simplest way to move reliably and attacking with as little actions as possible.

My findins are:
- There's no reliable way of moving with mouse move for MAIN1 is multi purpose
- The easiest way to attack is releasing a button and click a button (e.g. releasing MAIN1 and pressing right mouse button/Q/1 whatever). This is twice as many actions as pressing Shift.
- With MAIN1 held pressing another skill button makes you use that skill but in between the character will move also making it not usable.

IMO there should be a simple way to do the usual things: Moving and attacking.

Any suggestions?

**Comment by FeXoR-o-Illuria** [comment]
Actually sounds good. (Expecting an outcry from the old Diablo players ;p Maybe make it an option?)
Picking up items instead of attacking sounds much better than picking up items instead of fleeing.
NPCs may be a problem though since for some reason one can't move away any more while in conversation (one could in previous versions which I found easier than to first close the conversation and then move). This might lead to some situations.

I guess the character should not move while MAIN1 is pressed no matter the state of MAIN2 or Shift or which skill is assigned to MAIN1 (unless the movement is involved in the skill itself like Shield Bash I mean).

**Comment by dorkster** [comment]
>NPCs may be a problem though since for some reason one can't move away any more while in conversation (one could in previous versions which I found easier than to first close the conversation and then move).

Yep, looks like another bug. The player should definitely be able to move away from dialog, provided the dialog itself doesn't restrict movement. This is likely another artifact of trying to do everything with MAIN1. Switching to MAIN2 movement might even fix #1680, which apparently only happens when using mouse movement.

As for complaints from Diablo players, I wouldn't worry about it. Flare is not Diablo, and it's not like there aren't other ARPGs that use right-click to move. I'd rather not keep the current movement scheme around with all the issues it has.

**Comment by dorkster** [comment]
So I've [made the changes](https://github.com/flareteam/flare-engine/commit/eeffd7ae60316a799b8570864448c6c7984c3d2a) I mentioned. I really like it, and it no longer feels like I'm at a disadvantage compared to using keyboard movement. Let me know what you think.

**Comment by FeXoR-o-Illuria** [comment]
I think it's great!
As expected with a change like this it has a rat tail of consequences (though this is quite a beautiful rat in this case)
1) Inconsistent behaviour when the same keys are pressed but in different order
- MAIN2 (move) + Shift (Skill applied to MAIN2) + MAIN1 -> Skill applied to MAIN2
- MAIN2 (move) + MAIN1 (Skill applied to MAIN1 and a little movement in between) + Shift -> Skill applied to MAIN1
2) Now that the MAIN2 is used to move and items don't interfere with it IMO the item labels can always be shown (as the name of the setting "ALWAYS show loot labels" suggest). I don't know why the labels where hidden around the player but if it was the interaction with MAIN1 I would love to have that option fulfil the hopes it invokes by it's name again (I mean you run towards an item to pick it up and it's label you want to click fades away? Really?).
3) While my wish for an "attack move" doesn't have a mouse button left to be on what about MAIN1+Shift for that's free now? (However I'll file a separate request for that because I guess it's a bit more to change for that).


Also there's still the issue with the "little movement in between" that was there before but I think it's more a hindrance than useful.

Thanks a lot! Looks like you are about to get quite an improvement out of some simple bug reports after all ;)

**Comment by dorkster** [comment]
First, I want to address the "little movement in between" behavior. What you describe can also be seen when using keyboard movement, because the overall logic goes something like this:

1. Player is in the move state, but has hit an attack button.
2. The attack state is entered.
3. The attack is finished, so return to the idle stance.
4. From the idle stance, we can move or attack. Movement takes priority.
5. The player enters the move state.
6. Go to step 1.

I don't think your two examples are that much of a concern. Yes, all the same keys are pressed, but the order matters. Essentially, the first two buttons pressed determine the attack. In the first example, MAIN1 does nothing because we're already doing a different attack. In the second example, the MAIN1 attack is being executed, so Shift can only stop player movement.

----

As for the loot labels, they are now hidden when entities are nearby as per [this issue](https://github.com/flareteam/flare-engine/issues/1675) (pressing Alt will show everything). But I agree that doesn't fit the "Always show loot labels" description well. I think the old behavior should be enabled when that option is enabled, and the new behavior when the option is disabled. We'd be losing the option to hide all labels all the time, but that has limited usefulness.

I think what I'll ultimately do is remove the config menu option altogether and add a button in-game (likely under the minimap) that would toggle between all three styles. This way, players wouldn't have to exit the game to change that setting. *Side note: This could probably be done with other interface options, like adding a button to the Inventory screen to toggle auto-equipping items.*

----

Considering how elegant mouse-only controls are now, I'm not keen to add an "attack move" right away. Maybe in the future, though...

**Comment by FeXoR-o-Illuria** [comment]
Yea, the skill depending on order of pressed buttons isn't a big deal.
I can live with the "little movement in between" (I'll simply use MAIN2+Shift). But IMO it would be terrific if you could play just with the mouse without always have to press one button and release the other to change between move and attack (at least there is some time to release MAIN2 during the attack animation).

For the loot labels: The main issue (besides some flickering and the wording of the setting) is that they are hidden when the player is near. Isn't there a checkable difference between enemies and player to toggle this only for close enemies?
I like your idea with changing this ingame and the buttons at the minimap (and are not opposed to the two choices that would offer).

And, yes, "attack move" is definitely more a wish than a must have ;)

**Comment by dorkster** [comment]
>The main issue (besides some flickering and the wording of the setting) is that they are hidden when the player is near. Isn't there a checkable difference between enemies and player to toggle this only for close enemies?

Well, the original issue was that they were covering the player. So hiding them when the player was near ended up being the solution. Remember, you can hold the Alt key to force showing all loot labels.

**Comment by FeXoR-o-Illuria** [comment]
All good ;)
Thanks a lot!

**Comment by dorkster** [comment]
@FeXoR-o-Illuria I've added the button for changing loot tooltip visibility to the actionbar. The relevant commits are:

- https://github.com/flareteam/flare-engine/commit/5f5d26e04d5245752faeb3721d8cdcef0ec7e011
- https://github.com/flareteam/flare-game/commit/5e90491a6a5a337aaccbce260a9dda113dfed783

And since the original topic of this thread has been resolved, I'll close this.

**Comment by FeXoR-o-Illuria** [comment]
Perfect, thank you!
