### ISSUE TITLE
Several GUI interactions don't work when Alt pressed to show loot labels

### ISSUE THREAD

**Issue by FeXoR-o-Illuria** [flareteam/flare-engine#1686]
With Alt pressed to show loot labels at least the following GUI elements will not respond:
- Loot label (item not picked up)
- "Ingame window" buttons (Inventory not opened, pressing c/i/s/l works though)
- Close "ingame window" cross (window won't close)
- Items in inventory (item won't "stick" to cursor)

Additionally pressing MAIN2 (move) won't make the character move EDIT: (pressing Alt then MAIN1 then MAIN2 will though)

Additionally pressing Strg will "fix" most cases (but for items in inventory, may be intended anyway). Also pressing Shift makes the GUI elements react properly.

This seems strange to me for I'd guess one would like to see the items to either move towards them or pick them up if in range - both not working (as simple as this at least).

Is this intended/known?

EDIT:
Flare 1.08.21 (Linux)
But AFAICT the same in 1.08
This is independent of the "Always show loot labels" setting as far as I tested.

**Comment by dorkster** [comment]
All those interactions work for me when pressing Alt. Since you're on Linux, it's possible that your window manager is using the Alt input. For example, many window managers will use Alt + left click to move the window under the cursor. I changed my window managers shortcuts to use the Win key instead for this reason. If you don't want to change your window manager settings, you could try rebinding the "Alt" action in Flare to another key.

If it's not your window manager, perhaps it could be an N-key rollover issue with your keyboard?

**Comment by FeXoR-o-Illuria** [comment]
Yea, I was suspecting this is not Flare itself.

I'm using Xfwm4.
Alt by default is the zoom also working in Flare (turning it off didn't fix the issue).
Removing assignment "Settings Editor -> Xfwm4 -> easy_click" which was Alt fixed it (though with zoom_desktop=TRUE zoom won't work now, and whatever easy_click is supposed to tell the user ;p).

My keyboard seems to support up to 6 keys pressed simultaneously.

Definitely not a Flare issue though so feel free to close this issue, sorry for bothering you and, as always, thanks for your fast help ;)
