### ISSUE TITLE
Feature: Players should have a personal stash in addition to the shared stash

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1720]
The solution to get around players sharing level-scaled items between saves was to prevent stashing altogether. We could still let players store them in a per-save stash and remain fair.

**Comment by Sturwandan** [comment]
Can you please make shared stash to be opened by default when you click on stash?

**Comment by dorkster** [comment]
I prefer having the private stash be the default when first opening it. Perhaps we could remember the last tab that was selected so that you don't have to keep switching if you use the shared stash a lot.

**Comment by Sturwandan** [comment]
@dorkster, It turns out, I almost never use potions at all, since I don't have time for them during a fight and I can just wait for regeneration outside of a fight, and I only use scrolls which have spells which can't be bought (reflection and summoning), only during boss fights. And there is only two fights which can't be won without scrolls, unless you grind a lot: Metzger and Lezaith. Xonun and Mez are also difficult but I was able to defeat them without items. So, I would use shared stash more likely than private stash.
