### ISSUE TITLE
Arbitrary definition of resources (e.g. HP and MP)

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1776]
Currently, the engine has two fixed player resources: HP and MP. I think it would be a good idea to add some flexibility here. HP is pretty standard, but MP might not fit the theme of many games. Instead of MP, maybe a game would want to define this resource as "Energy" or something similar. It may also be desirable to add more resources, such as "Stamina".

The process for implementing this should be similar to when we added arbitrary primary stats.

**Comment by WithinAmnesia** [comment]
So con you confirm that if this works I could be able to create a 'Spirit' resource alongside 'Mana'; and abilities could require X amount of 'Spirit' and or X amount of 'Mana'? Also can HP and MP be able to be renamed to 'Health' and Mana' with this feature as well?

**Comment by dorkster** [comment]
That is correct. You'll be able to have more than one non-HP resource, and all resources will be able to have arbitrary names.

**Comment by WithinAmnesia** [comment]
Also with this feature can I also able able to add a 'Spirit' resource bar for the HUD beside the 'Mana' resource bar?

**Comment by dorkster** [comment]
Yes, a filename for a statbar menu will be one of the properties of a resource.

**Comment by WithinAmnesia** [comment]
Can HP be able to have an arbitrary name like how elements work? For example 'Health' or 'Hit Points' or even ~'Hull Structure' (for people wanting to make Sci-Fi Flare engine games?). I take that there is a plan for arbitrary names for arbitrary resources where resource like these could be possible 'Mana' and 'Spirit'?

**Comment by WithinAmnesia** [comment]
I'm hoping to have "Health" "Mana" and "Spirit" with (at least) +0.1% to -0.9% or -0.1% to 0.9% to 'Health' or 'Mana' or 'Spirit'. With stats like -0.1% Health Regeneration or -0.1% Mana Regeneration or -0.1% Spirit Regeneration (and +X% Regeneration as well). Also + or - % to total 'Health' or 'Mana' or 'Spirit'. I am not sure if this is possible in Flare but I think Diablo II has this as well + or - % to current 'Health' or 'Mana' [or 'Spirit'].
-Total health/mana/spirit % is like + or - 10% of 75 / 100 Health/Mana/Spirit = + / - 10 health/mana/spirit.
- Current health/mana/spirit % is like + or - 10% of 75 / 100 Health/Mana/Spirit = + / - 7.5 health/mana/spirit.
Also does the Flare Engine round up or down with something like + / - 7.5? 

I am hoping to make the core of my video game's progression around itemization and creature attributes that are near mirrors of the player attributes. These 1.14, arbitrary resources, % and fractional decimal values are key / core elements / pieces of my progression system / game design. I would like to get the 'game play core' / player progression working, attributes with statistics and elements working (1.14 issues), get the abilities / skill tree and play style progression working (skill tree horizontal scroll bar), creature encounter attributes and abilities and random drop table reward system working (needs skill tree testing), quests and other elements of civilization interaction (e.g. questing, trading and crafting) working (these are 9/10 working, maybe mercenaries / pets but that is a bonus for later; possibly reasonable ~'player housing' down the road).

I wish to do all of that before making the art and areas look very pretty. I want to get the 'core gameplay' / 'core player progression' working before I go crazy on the art and level design. For all of those visual details are mostly for making a video game 'wide'. Yet I feel that I need to get my video game to be 'deep' first to get my properties straight and be efficient with my time and avoid mechanic / core gameplay bloat and log jams and avoid retrofit hell (like with my RPG Maker nightmare XD).

I have been experimenting / tinkering to find what is doable / feasible for art and other 'wide' areas. I hope to avoid retrofit hell and have all of the major gameplay building tools ready to start building a core first (hopefully deep) chunk of my overall video game plan first to get my priorities straight and make a well 'core' of player progression and content experience for my video game.

Flare is successfully proven / experimented to work with 4K art assets and to I found run smoothly and be future proof for the 2020's and 2030's with the power offered from the 64-bit executable. A solution has been found for making 4K animations and tilesets for Flare. I have a rough working prototype for dual wielding and an ad hoc animation system 2H weapons; both of these can work with Flare 4K. Enough to build out a future proof / reasonably grow-able prototype that can support key gameplay experience components for my video game from the start. Also of which working prototype components can be feasibly replaced in retrospect for better polish. As in swapping out the working prototype animations for dual wielding and 2H animations with better player presentation versions without breaking the game engine in the future. I also just recently found a working solution to render Flare 4K high resolution tileset assets in 8 directions (4 conventional angle renders plus 4 changed angle renders to build out 8 direction renders for tilesets).

All of these Flare engine and art, mechanics and concept feasibility experiments and proof of concepts I have been working on to see what 'creative' tools I can have to work within my 'creative tool box' at the approximate start of building the core of my video game. I am hoping to have all of my 'core creative tools' at the start and make sure I can get all of the critical 'core creative tools' first before I make ~50 areas of 1,000 x 1,000 tiles populated with ~2,000+ creatures and other layers of depth and player progression and exploration systems interwoven throughout the first initial 'large chunk' of my overall video game world design developed hopefully for a 'commercially viable' video game of which I hope is worth playing.

I don't want to pressure / rush anything; that is not how I operate. Yet I figured to get some clarity / share my perspective / tell why am I doing what I am doing to hopefully give reasonable explanations as to what I am up to; and where I hope to go in the near future. Also to kind of who where I am at with all of this related work for all of this Flare related video game development. 

I hope to not be too overly wordy / become over-encumbersome in my medium of communication / waste people's time and focus. Yet I do wish to be understood if possible with high details of detail; if people are interested that is. So I hope this general overview of my immediate flare development related plan / loose structure / ~'work flow skeleton' gives insight to my mode of operation. I hope to not keep asking for feature after feature either for that can become wasteful of people's time and good will after a point. So whatever I do I am trying to avoid feature bloat and stay focused on this 'core game play experience' with trying to get my decades aged game play designs translated into a video game without going nuts and trying to stay reasonable and on track to avoid feature bloat, workflow bottle necks and most of all retrofit hell. I realize that I cannot make massive mistakes with engine development and wasting people's time asking for too much and being unseasonable in my requests. Thus I must stay on track for 'low input high output' to keep the dreams alive of single developers making great games that can go toe to toe with the titans of industry and win. I do try to fight for features that have the potential to give a big increase to the overall play experience; Deep Arbitrary Attributes and Statistics for Deep Itemization, Multiple Layered Creature (e.g. Humanoid) Sprite Animations for Deep Encounter Possibilities, Flare 4K for 2020's and 2030's Fighting Chance at Creating Classic Video Games, Dual Wielding and 2H Animation Support for Deep Character Play-style Diversity and Customization, 8 Direction Flare Tileset Rendering Tileset Art Asset Standards for intuitive non contrived 'natural looking game worlds that are still within reason (even with tiled art assets Flare ecosystem video game can compete and win verses full 3D games).

All of these kinds of features are more than I feel comfortable to ask for and a lot of the solutions that I provided I went in blind with a hope and the will power to keep failing until I found a working prototype. Every solution provided by the community and especially @dorkster are something that I treasure for I know the value of theses often high complexity solutions. For I know how hard it is to battle with difficult high complexity problems. Often where there are many rounds of initial discouraging and frustrating failures and or requiring years of skill mastery to earn victory with and find ways to properly solve. Also I feel guilty asking for anything more than I absolutely would struggle perhaps indefinitely with in the near future with. Most all of every ask and or request I currently have in the Github 'Issues' pages of the Flare Engine and Flare Game I try hard to not have more than I absolutely require within reason, feasibility and in keeping / upholding with and operating in good faith and in good will of the community (also to be legal as well if I find the issue to be within ~'murky waters'). I have more things I would like (up-gradable player housing, wow-like enchanting, diablo-like gems and item socket support, epic sieges and ruling castles with chunks of land and settlements, online support etc.) yet these are not necessary to start building a core and or they are overly complex and or not reasonable nor feasible to ask for on a pro bono basis given the high complexity and or work load present for possible solutions.

So I try to ask only for things I absolutely need to build core of my video game. I need to stay away from 'wouldn't it be cool if so and so and bla bla bla?' / feature creep in order to stay focused. So as to stay away from endless feature bloat / creep and to keep on track for hopefully a successful efficient work flow and reasonable / do-able development path / make it happen / build and realize for an already ambitious multi-decade project that I have been struggling to get to the point where I am at now. To build a powerful deep core for a video game with all of the deep player progression and itemization systems and mechanics. To get all of these ambitious player experience and progression systems into a big full fledged / video game-afide / realized video game playable world of my medieval fantasy setting. Finally to become a video game developer with full creative power and to be able to be paid for my work and to more over to be able to empower a world community that wants to play games worth playing.

It feels kind of surreal being so close after so many years of failing and failing to get closer and closer and more and more creatively powerful after each failure, near miss and salvaged video game development project after salvaged video game development project. I started out playing video games on 80's and 90's [also I think an Atari and a Sega)] consoles in the mid to late 90's as soon or earlier than I could properly hold a controller (I remember gumming a SNES controller and seeing the dark world on screen from Zelda aLttP when I was at least a 1 year old XD). I remember being amazed and wanting more to experience in each video game world behind each mystery and secret and every sense of wonder that populated these early video games of my childhood. These every video game experience where often on the Super Nintendo Entertainment System with such examples as The Legend of Zelda A Link to the Past, Super Mario RPG, J.R.R. Tolkien's The Lord of the Rings, Vol. I, Also with NES mixed in with various Final Fantasies, Castlevanias, Dragon Quest, Aladdin / Princes of Persia etc. Also I liked the N64 Zelda Ocarina of Time, Banjo Kazooie and Tooie and Turok and Super Mario 64 + Mario Kart 64 and Golden Eye as well. I was 9 years old and I could not read but I first played Diablo 1 on a floppy disk, I got to the butcher at my grandmother's place and then all the gore was cool to myself but not my grandma lol. I then banned from Diablo 1 I played Baldur's Gate Tales of the Sword Coast in 2005 and pretty much since then I have been on this journey to make a great video game series worth playing.

Early 2000's / Old School Runescape and 2000's World of Warcraft also inspired myself to create something truly special for the entire world to enjoy together as one rich or poor. I think after 15 years playing World of Warcraft retail from 2007 TBC launch until 2010, free accounts to mess around with low level areas until MoP in 2012, then I hoped around private servers in 2012 (custom custom servers like Heroes WoW and Chaos WoW I remember briefly), then I played Molten WoW [WotLK] from ~2012 to the Moltdown in 2015, then I started playing on Kronos WoW [the known world's greatest private server of arguably the known world's greatest M.M.O.R.P.G.] in 2015 and played vanilla WoW until early 2020 after farming end game Naxxramas (hard core raiding with my old Guild Unite and Vanquish from 2018-2019) on multiple characters and getting BiS on my 300 ms Ping Night Elf Warrior Veldryn, then helping the server keep raiding end game / progress through Naxxramas on a composite 'survivor' guild called Legacy from 2019 to 2020 after WoW Classic retail launched in 2019 that gutted the server, in 2019 I think started to play a custom vanilla WoW server called Turtle WoW and I help a bit with development with items / quests / end game from 2019-2021. I last raided Naxxramas on Kronos in 2021 as a guild anniversary get together event after a year of not playing on Kronos. I recorded the whole raid and saved other people's videos and how usual Ping high level hard core player gameplay from a guildy's twitch stream of the whole raid. I started hard core raiding wow to understand what the highest point of an MMORPG progression could be to experience; I did so just 2 runs before Unite and Vanquish stopped raiding and went to Retail Classic WoW; after over 12 months without missing a raid I earn [Gressil, Dawn of Ruin](https://vanilla-twinhead.twinstar.cz/?item=23054); the best in slot main hand weapon of melee characters and the most aught after item bar none in all of vanilla World of Warcraft]. I was not the best Warrior literally in the world with 300 ms ping but I was the most dedicated Warrior and I still got to the very top even with 300 ms of Ping (where when I logged on at least 40% of my D.P.S. was gone and I was mechanically unable to properly main tank); good enough for top 10 active Warriors in the world. I went to the very top so that I could be close to the spirit of wonder and challenge and the journey of the deepest most challenging kind of progression to experience. The irrefutable greatest raiding guild of classic Everquest, Fires of Heaven was the home of the core staff who where hired onto World of Warcraft to create the raiding and end game experience and progression in the 2000's World of Warcraft. I wanted to not guess and wonder what that could mean in terms of innate understanding of player progression that enables world leading game design; I wanted to live that just like the legends of old and so I did. I keep going back to classics of the past so I can hope to understand what the 'soul' of these great works is on an innate level so that I can see what the creators were aiming at and trying to realize. So that when I make my works of creation that I am not trying to emulate other';s success but to take up the mantle and uphold and be worthy of the same 'fire of god' / innate fulfillment of creation that drove those great creators of old to new heights of wonder and awe that inspired world of generations with a body of work that we now understand as immortal timeless classics; extremely influential if not supernatural pillars of medieval fantasy.

I think in 2022 I have fully switched gears to start fully working toward a commercially viable video game of my own medieval fantasy universe. So I keep working away on a multi-decades old dream that is almost as old as I am. Perhaps I was born to make video games, perhaps that is what I will be doing until I die. I don't know how long I will live yet what ever I do I want to work towards realizing this deep dream of mine and share these visions of beauty, senses of wonder and experiences of awe with the entire world. I hope to make an everlasting gem crystalized from the wonders of the deepest of dreams and share its brilliance with the entire world to enjoy; man or woman, old or young, rich or poor, together as one.

**Comment by dorkster** [comment]
>Can HP be able to have an arbitrary name like how elements work? For example 'Health' or 'Hit Points' or even ~'Hull Structure' (for people wanting to make Sci-Fi Flare engine games)? I take that there is a plan for arbitrary names for arbitrary resources where resource like these could be possible 'Mana' and 'Spirit'?

Yes, all the resources will be able to have custom names. The HP stat will still be referenced as `hp` in the config files because it's a special case. But the in-game display name will be able to be changed.

**Comment by WithinAmnesia** [comment]
Okay, thank you for the clarity.

**Comment by WithinAmnesia** [comment]
Are arbitrary definition of resources still planned / needed or has something come up in with adding to the engine made this kind of redundant (like how making infinite talent tree tabs kind of made horizontal scrolling redundant)? Or is there something else I am not thinking about?

**Comment by dorkster** [comment]
It's still planned. I've just shifted it back in favor of scaled items & item generation, which I think are more desired features. I marked it for 1.15, but it may happen for 1.14 depending on how I feel about the eventual implementation.

**Comment by WithinAmnesia** [comment]
> It's still planned. I've just shifted it back in favor of scaled items & item generation, which I think are more desired features. I marked it for 1.15, but it may happen for 1.14 depending on how I feel about the eventual implementation.

Okay that makes sense. I do a lot of what I work on based on how I feel over all. I am quite logical but at times I let the Monkey Lizard Brain win at times (usually when I am really tired or bored) [as evidenced here: https://github.com/flareteam/flare-engine/issues/1784#issuecomment-1186717498 ] so everyone is different. I think most everyone likes ice-cream and I wish I could give you some but there are computers after all even if my monkey lizard brain thinks that is right thing to do XD.

So I hope this all works out and you still find ways to have a bit of fun or what not. When I work I try to make my Monkey Lizard brain happy and it can cure / battle depression / stress / logical hard times and give myself motivation and restore a sense of fun and discovery. So I hope this all works well for you and you can find fullfilment and joy in all of this :-D.

**Comment by WithinAmnesia** [comment]
This is the last major feature I could ever ask to be implemented to Flare to empower myself to make my dream video game on Flare. I sincerely hope that this feature gets added to the Flare engine. Even if its the last feature I would be empowered to finally bring my dreams to life and have a third resource ~'Spirit' that I have had locked away in my concept books of the medieval fantasy world for years and years that I have been working on for decades. I sent you an Email @dorkster with more details.

**Comment by dorkster** [comment]
Don't worry. This is still on the roadmap.

I've been rethinking the potential implementation. The existing parts of the mod API that deal with HP and MP don't need to be integrated into this feature in its initial form. I think as long as there's a way to hide the MP stat, this can stand alone as its own thing.

**Comment by WithinAmnesia** [comment]
Okay. I'd be happy with a third resources called "Spirit" or "SP" and still have HP and MP for a partial implementation.

**Comment by dorkster** [comment]
Status update: I'm getting close to finishing this feature. Remaining tasks include

- Healing-over-time status effects
- Stealing status effects
- An extension to `requires_hpmp_state` for Powers
- Some UI stuff (tooltips, etc)
- Probably some other small things I forgot

I'm looking to finish it this week and get 1.14 out the door. In the meantime, here's the example configuration I've been using that adds a Stamina stat.

```
[resource_stat]
# engine keys
## base
stat_base=stamina
stat_regen=stamina_regen

## steal/leech
stat_steal=stamina_steal
stat_resist_steal=resist_stamina_steal

## effect heal-over-time
stat_heal=stamina_heal
stat_heal_percent=stamina_heal_percent



# menu
menu_filename=menus/resource_stamina.txt



# text that can be translated
text_base=Max Stamina
text_base_desc=Total amount of Stamina.

text_regen=Stamina Regen
text_regen_desc=Ticks of Stamina regen per minute.

text_steal=Stamina Steal
text_steal_desc=Percentage of Stamina stolen per hit.

text_resist_steal=Resistance to Stamina steal
text_resist_steal_desc=Percentage chance that Stamina steal will be negated.

text_combat_heal=ST
text_log_restore=Stamina restored.
text_log_low=Not enough Stamina.
text_tooltip_heal=Stamina per second
text_tooltip_cost=Stamina cost
```

![Screenshot_20221204_161055](https://user-images.githubusercontent.com/913982/205516245-a83de3aa-67d1-41b2-b96a-b2778771e034.png)

**Comment by WithinAmnesia** [comment]
That is a dream come true Justin! That looks sooo amazing so far! This is MASSIVE progress. This literally is the keystone feature I've been hoping to get for over a year now and with it I can start large scale itemization and start fleshing out the progression and core gameplay of my RPG.

**Comment by WithinAmnesia** [comment]
This resource system be affected by player equipped item stats like '+10 Max Stamina'? Or -7.3% Stamina Regeneration?

**Comment by dorkster** [comment]
>This resource system be affected by player equipped item stats like '+10 Max Stamina'? Or -7.3% Stamina Regeneration?

Yes. Everything you can do with MP will be possible here. `stat_base`, `stat_regen`, `stat_steal`, and `stat_resist_steal` will all be able to be used for item / power bonuses. `stat_heal` and `stat_heal_percent` will be able to be used for powers.

**Comment by WithinAmesia** [comment]
So in theory 4 or more resource bars could be supported from this not only 3? Such as 'Health' 'Stamina' 'Spirit' and 'Mana' for example or whatever people come up with; (I know WoW has over 4 difference class resources)?

**Comment by dorkster** [comment]
>So in theory 4 or more resource bars could be supported from this not only 3? Such as 'Health' 'Stamina' 'Spirit' and 'Mana' for example or whatever people come up with; (I know WoW has over 4 difference class resources)?

Correct. You can have multiple `[resource_stat]` sections in the config file.

**Comment by dorkster** [comment]
Completed:

- https://github.com/flareteam/flare-engine/commit/085bb02040b254f1d1efbf0797ea2d6df0c99ca2
- https://github.com/flareteam/flare-engine/commit/bac5224c1d37fcf916352af73a9ae067b8ea12ef

**Comment by WithinAmnesia** [comment]
@dorkster How does one get the character menu screen to show the arbitrary resource stats?
What things am I doing incorrect? I got the 4 resource bars to show up on the HUD (Health, Vigour, Spirit, Mana) and use stat values scaling based upon primary stat values yet I cannot seem to get 'Vigour' and 'Spirit' to display in the character menu screen with the rest of the stats.
Engine files:
[resource_stats.txt](https://github.com/flareteam/flare-engine/files/10201651/resource_stats.txt)
[stats.txt](https://github.com/flareteam/flare-engine/files/10201652/stats.txt)
[primary_stats.txt](https://github.com/flareteam/flare-engine/files/10201654/primary_stats.txt)
[elements.txt](https://github.com/flareteam/flare-engine/files/10201655/elements.txt)
[damage_types.txt](https://github.com/flareteam/flare-engine/files/10201657/damage_types.txt)
Menus Files:
[character.txt](https://github.com/flareteam/flare-engine/files/10201660/character.txt)
[hp.txt](https://github.com/flareteam/flare-engine/files/10201661/hp.txt)
[mp.txt](https://github.com/flareteam/flare-engine/files/10201662/mp.txt)
[Vigour.txt](https://github.com/flareteam/flare-engine/files/10201663/Vigour.txt)
[Spirit.txt](https://github.com/flareteam/flare-engine/files/10201664/Spirit.txt)
Images/Menus Files:
![Bar_Health](https://user-images.githubusercontent.com/86871191/206891297-39d04c3b-7e02-4593-b1f7-a411e5b9e5ae.png)
![Bar_Health_Background](https://user-images.githubusercontent.com/86871191/206891303-c11f43ab-9951-4569-bf57-6aec3e8faba3.png)
![Bar_Vigour(Hue+100)](https://user-images.githubusercontent.com/86871191/206891314-c1b967b9-12d6-4be2-bae5-b309390dd07b.png)
![Bar_Vigour_Background](https://user-images.githubusercontent.com/86871191/206891319-30946482-7832-4385-adca-df3ca7da2144.png)
![Bar_Spirit(Hue+69)](https://user-images.githubusercontent.com/86871191/206891326-a81672b1-45c1-49b1-b224-7eeae1759941.png)
![Bar_Spirit_Background](https://user-images.githubusercontent.com/86871191/206891333-f2dfdaad-135b-4f22-ade8-95e84bd94c79.png)
![Bar_Mana](https://user-images.githubusercontent.com/86871191/206891337-137680fd-062f-4594-8248-bc5e981bc927.png)
![Bar_Mana_Background](https://user-images.githubusercontent.com/86871191/206891340-930eb3d8-db1c-4e26-ad58-15a5c4078ac4.png)
Please feel free to ask any more required files I'd be more than glad to share them.
P.S. Also is it possible for 'HP' and 'MP' be renamed to something like Health (from 'HP') and Mana (from 'MP') respectively or are we stuck with 'HP' and 'MP'?

**Comment by dorkster** [comment]
In `menus/character.txt`, add the following lines:

```
show_stat=vigour,true
show_stat=vigour_regen,true
show_stat=vigour_steal,true
show_stat=resist_vigour_steal,true

show_stat=spirit,true
show_stat=spirit_regen,true
show_stat=spirit_steal,true
show_stat=resist_spirit_steal,true
```

Just change true to false if there are any that you want to hide.

>P.S. Also is it possible for 'HP' and 'MP' be renamed to something like Health (from 'HP') and Mana (from 'MP') respectively or are we stuck with 'HP' and 'MP'?

There's currently no way to change HP and MP. But you *can* hide the MP bar by adding `enabled=false` to `menus/mp.txt`, and then create a custom resource named "Mana". Though I doubt there would be much point in doing that where you can't change HP.

**Comment by WithinAmnesia** [comment]
@dorkster How does one use these arbitrary stats on items such as +1.6% Spirit, -3.72% Spirit Regeneration, +0.75% Vigour Regeneration or -2.1% Vigour and have the item work and have the tool tip display?

**Comment by dorkster** [comment]
Basically, you take the desired value, add it to 100, and then append a % sign. So for your 4 examples:

```
bonus=spirit,101.6%
bonus=spirit_regen,96.28%
bonus=vigour_regen,100.75%
bonus=vigour,97.9%
```

**Comment by WithinAmnesia** [comment]
@dorkster  Where can engine/number_format.txt be found? https://github.com/flareteam/flare-engine/commit/7f67785877a8d8f4b9e379c81fc26075d6e17944

Do I have to make number_format.txt then put it under engine folder and then take my best guess at making the number_format.txt yet I feel I'm missing a step somewhere?

**Comment by dorkster** [comment]
Yes, you will need to add it yourself. The [attributes](https://github.com/flareteam/flare-engine/wiki/Attribute-Reference#enginesettings-number-format) should be pretty simple to understand.

For example, if you wanted 3 digits after the decimal place in item tooltips, all you need is:

```
# engine/number_format.txt
item_tooltips=3
```
