### ISSUE TITLE
Fog-of-war: Minimap representation sometimes doesn't match fog layers

### ISSUE THREAD

**Issue by dorkster** [flareteam/flare-engine#1798]
See comment here: https://github.com/flareteam/flare-engine/pull/1795#issuecomment-981185380

>However, I noticed a bug with the minimap and fog-of-war that existed before these optimizations. In short, the minimap didn't update correctly near the edges of the map. My "[solution](https://github.com/flareteam/flare-engine/commit/14c0059b5d5208f88f01a80aef848da4d61eee23)" was to make the minimap update whenever the dark layer OR the fog layer changes. The bug is still there, but more frequent updating let's the player force the map to load by getting closer to the wall.

>Here's a [video](https://i.imgur.com/TWeuIrO.mp4) demonstrating it. Notice how the there are still gaps in the minimap when all the dark tiles are discovered. Only when I move closer does the minimap update.

**Comment by r-a-cristian-93** [comment]
I did some investigation too, and i have noticed that the bug was there before minimap optimisations.

Trying to fix it i have identified one of the thing that are causing this problem. The clip that is passed here seems to be too small and drawPixel() function is rejecting a lot of pixels.https://github.com/flareteam/flare-engine/blob/dd1da511399f2a95a544daf5f236fcda1b91a7db/src/MenuMiniMap.cpp#L551

**Comment by dorkster** [comment]
I'm not so sure that's the culprit. I tired beginPixelBatch() without the clip parameter and saw the same bug.

**Comment by dorkster** [comment]
Nevermind, you were right. I had tried removing the clip *before* my patch. It seems to work better now (although not perfect), so the clip size is most likely one factor.
