### ISSUE TITLE
Calling setActiveTab in WidgetTabControl while no tabs are active can cause SIGSEGV

### ISSUE THREAD

**Issue by Daggersoath** [flareteam/flare-engine#1838]
WidgetTabControl line 93  performks a loop with i starting at tab, then continuing to check if tab < tabs.size().
If no tabs are active, this continues into unallocated memory.

Problem:
`for (unsigned i = tab; tab < tabs.size(); ++i)`

Fix:
`for (unsigned i = tab; i < tabs.size(); ++i)`

I would fix this and do a pull requested but I can't create more than one fork and I have a lot of changes that don't want to be merged into the engine.

**Comment by dorkster** [comment]
Good catch. Should be [fixed](https://github.com/flareteam/flare-engine/commit/faf8f7a74c5863648ec22d06b6deb60faf345677) now.

Were you actually able to trigger this in-game? I think in most cases, we always have at least one active tab set. So I'm not sure where it could happen in practice.

>I would fix this and do a pull requested but I can't create more than one fork and I have a lot of changes that don't want to be merged into the engine.

You don't need to make multiple forks in order to work on different change sets. With git, you can easily create a "branch" for what you want to work on, e.g.: `git checkout -b widgettabcontrol_fix`.

**Comment by Daggersoath** [comment]
Thanks :)

I am working on adding multiplayer to the engine and created a copy of the config menu. During my modifications I ended up with no active tab for one of the menus and it crashed.

Oh cool, I shall make sure to do that in future :)
